// Generated by 'Export TypeScript Sprites' Aseprite Extension
import url from "./sprites.png"
export const tile_grass_1 = { url, x: 0, w: 16, h: 16, y: 16, };
export const missing_sprite = { url, x: 0, w: 16, h: 16, y: 0, };
export const mob_druid_idle_2 = { url, x: 13, w: 13, h: 18, y: 46, };
export const mob_druid_idle_1 = { url, x: 0, w: 13, h: 18, y: 46, };
export const tile_grass_2 = { url, x: 16, w: 16, h: 16, y: 16, };