// Generated by 'Export TypeScript Sprites' Aseprite Extension
import url from "./sprites.png"
export const tile_grass_1 = { url, x: 0, w: 16, h: 16, y: 16, };
export const missing_sprite = { url, x: 0, w: 16, h: 16, y: 0, };
export const object_druid_idle_2 = { url, x: 13, w: 13, h: 18, y: 46, };
export const object_druid_idle_1 = { url, x: 0, w: 13, h: 18, y: 46, };
export const tile_grass_2 = { url, x: 16, w: 16, h: 16, y: 16, };
export const shadow = { url, x: 0, w: 14, h: 5, y: 41, };
export const object_tree_1 = { y: 79, url, x: 0, w: 25, h: 33, pivot: { x: 12, y: 29, }, };
export const object_tree_2 = { y: 78, url, x: 25, w: 23, h: 34, pivot: { x: 11, y: 31, }, };
export const object_tree_3 = { y: 74, url, x: 48, w: 24, h: 38, pivot: { x: 13, y: 35, }, };
export const object_tree_4 = { y: 76, url, x: 72, w: 26, h: 36, pivot: { x: 13, y: 33, }, };
export const object_tree_5 = { y: 74, url, x: 98, w: 22, h: 38, pivot: { x: 11, y: 35, }, };
export const object_tree_6 = { y: 71, url, x: 120, w: 25, h: 41, pivot: { x: 13, y: 38, }, };
export const object_tree_7 = { y: 70, url, x: 145, w: 24, h: 42, pivot: { x: 10, y: 38, }, };
export const object_tree_8 = { y: 71, url, x: 169, w: 24, h: 41, pivot: { x: 10, y: 38, }, };
export const object_centurion = { y: 43, url, x: 26, w: 18, h: 21, pivot: { x: 10, y: 20, }, };
export const ui_targeting_dot = { url, x: 16, w: 3, h: 4, y: 0, };
export const decoration_grass_1 = { url, x: 0, w: 8, h: 8, y: 32, };
export const decoration_grass_2 = { url, x: 8, w: 8, h: 8, y: 32, };
export const decoration_grass_3 = { url, x: 16, w: 8, h: 8, y: 32, };
export const decoration_grass_4 = { url, x: 24, w: 8, h: 8, y: 32, };
export const decoration_reed_1 = { url, x: 32, w: 5, h: 5, y: 35, };
export const decoration_reed_2 = { url, x: 37, w: 5, h: 5, y: 35, };
export const decoration_reed_3 = { url, x: 42, w: 5, h: 5, y: 35, };
export const decoration_alt_grass_1 = { url, x: 47, w: 5, h: 5, y: 35, };
export const decoration_alt_grass_2 = { url, x: 52, w: 7, h: 6, y: 34, };